Add my new widgets project
learn-web-development-my-idea-my-way/learn-react-redux pull request #13
Opened 2021-01-20 15:39 UTC by rohitksp

2021-01-20 16:00 UTC, nrchandan requested changes

2021-01-20 16:00 UTC, nrchandan commented on rohit/widgets/.eslintcache
> +[{"/home/rohit/Documents/React-Learn/widgets/src/index.js":"1","/home/rohit/Documents/React-Learn/widgets/src/App.js":"2","/home/rohit/Documents/React-Learn/widgets/src/componets/Accordion.js":"3","/
I guess we shouldn't commit this file.

2021-01-20 16:00 UTC, nrchandan commented on rohit/widgets/src/componets/Accordion.js
> +import React, { useState } from 'react';
There's a spelling mistake in the name of the "components" folder.

2021-01-20 16:12 UTC, rohitksp commented on rohit/widgets/.eslintcache
> +[{"/home/rohit/Documents/React-Learn/widgets/src/index.js":"1","/home/rohit/Documents/React-Learn/widgets/src/App.js":"2","/home/rohit/Documents/React-Learn/widgets/src/componets/Accordion.js":"3","/
Okay

2021-01-21 15:31 UTC, komal7292 approved these changes

2021-01-21 15:43 UTC, nrchandan commented on rohit/widgets/src/App.js
> +import Search from './componets/Search'
Folder name is still incorrect in the code.

2021-01-21 15:43 UTC, nrchandan commented on rohit/widgets/src/components/Accordion.js
> +  const renderedItems = items.map( (item, index)=> {
Let's pay more attention to code formatting. There should be spaces around operators/symbols.

2021-01-21 15:59 UTC, nrchandan commented on rohit/widgets/src/App.js
> +//import Accordion from './componets/Accordion';
Rohit, please pay attention when fixing errors. Fix not just one error or one line, but look around for more of such errors.

2021-01-21 15:59 UTC, nrchandan approved these changes

2021-01-21 15:59 UTC, merged