Completed section 12 widgets
learn-web-development-my-idea-my-way/learn-react-redux pull request #21
Opened 2021-01-26 15:18 UTC by rohitksp

2021-01-26 16:05 UTC, nrchandan requested changes
Just a minor issue. However, I see a console warning that you should probably fix.

src/components/Search.js
  Line 36:6:  React Hook useEffect has a missing dependency: 'results.length'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

2021-01-26 16:05 UTC, nrchandan commented on rohit/widgets/src/App.js
> +      <Translate options={options}  />
The `Translate` component does not expect any prop. 
```suggestion
      <Translate />
```

2021-01-26 16:05 UTC, nrchandan commented on rohit/widgets/src/components/Dropdown.js
> +  );
Thank you for removing this trailing space. It's important to keep the code clean.

2021-01-27 13:02 UTC, komal7292 approved these changes

2021-01-28 04:33 UTC, closed without merging